require "LOL"

Hero = LOL.new_class()

function Hero:initialize(name)
	self.name = name
end

BruceWillis = LOL.new_class(Hero)

function BruceWillis:initialize(name, film)
	BruceWillis.super.initialize(self, name)
	self.film = film
end

hero = Hero:new()
john_mcclane = BruceWillis:new("John McClane", "Die Hard")

print("\nBase class\n----------")
print("  Hero:is_class()    => " .. tostring(Hero:is_class()))
print("  Hero:is_instance() => " .. tostring(Hero:is_instance()))
print("  hero:is_class()    => " .. tostring(hero:is_class()))
print("  hero:is_instance() => " .. tostring(hero:is_instance()))

print("\nDerived class\n-------------")
print("  BruceWillis:is_class()     => " .. tostring(BruceWillis:is_class()))
print("  BruceWillis:is_instance()  => " .. tostring(BruceWillis:is_instance()))
print("  john_mcclane:is_class()    => " .. tostring(john_mcclane:is_class()))
print("  john_mcclane:is_instance() => " .. tostring(john_mcclane:is_instance()))

print("\nInheritance\n-------------")
print("  Hero:is_ancestor_of(Hero)                    => " .. tostring(Hero:is_ancestor_of(Hero)))
print("  Hero:is_ancestor_of(hero)                    => " .. tostring(Hero:is_ancestor_of(hero)))
print("  Hero:is_ancestor_of(BruceWillis)             => " .. tostring(Hero:is_ancestor_of(BruceWillis)))
print("  Hero:is_ancestor_of(john_mcclane)            => " .. tostring(Hero:is_ancestor_of(john_mcclane)))
print("  hero:is_ancestor_of(Hero)                    => " .. tostring(hero:is_ancestor_of(Hero)))
print("  hero:is_ancestor_of(hero)                    => " .. tostring(hero:is_ancestor_of(hero)))
print("  hero:is_ancestor_of(BruceWillis)             => " .. tostring(hero:is_ancestor_of(BruceWillis)))
print("  hero:is_ancestor_of(john_mcclane)            => " .. tostring(hero:is_ancestor_of(john_mcclane)))
print("  BruceWillis:is_ancestor_of(Hero)             => " .. tostring(BruceWillis:is_ancestor_of(Hero)))
print("  BruceWillis:is_ancestor_of(hero)             => " .. tostring(BruceWillis:is_ancestor_of(hero)))
print("  BruceWillis:is_ancestor_of(BruceWillis)      => " .. tostring(BruceWillis:is_ancestor_of(BruceWillis)))
print("  BruceWillis:is_ancestor_of(john_mcclane)     => " .. tostring(BruceWillis:is_ancestor_of(john_mcclane)))
print("  john_mcclane:is_ancestor_of(Hero)            => " .. tostring(john_mcclane:is_ancestor_of(Hero)))
print("  john_mcclane:is_ancestor_of(hero)            => " .. tostring(john_mcclane:is_ancestor_of(hero)))
print("  john_mcclane:is_ancestor_of(BruceWillis)     => " .. tostring(john_mcclane:is_ancestor_of(BruceWillis)))
print("  john_mcclane:is_ancestor_of(john_mcclane)    => " .. tostring(john_mcclane:is_ancestor_of(john_mcclane)))
print("  Hero:is_descendant_of(Hero)                  => " .. tostring(Hero:is_descendant_of(Hero)))
print("  Hero:is_descendant_of(hero)                  => " .. tostring(Hero:is_descendant_of(hero)))
print("  Hero:is_descendant_of(BruceWillis)           => " .. tostring(Hero:is_descendant_of(BruceWillis)))
print("  Hero:is_descendant_of(john_mcclane)          => " .. tostring(Hero:is_descendant_of(john_mcclane)))
print("  hero:is_descendant_of(Hero)                  => " .. tostring(hero:is_descendant_of(Hero)))
print("  hero:is_descendant_of(hero)                  => " .. tostring(hero:is_descendant_of(hero)))
print("  hero:is_descendant_of(BruceWillis)           => " .. tostring(hero:is_descendant_of(BruceWillis)))
print("  hero:is_descendant_of(john_mcclane)          => " .. tostring(hero:is_descendant_of(john_mcclane)))
print("  BruceWillis:is_descendant_of(Hero)           => " .. tostring(BruceWillis:is_descendant_of(Hero)))
print("  BruceWillis:is_descendant_of(hero)           => " .. tostring(BruceWillis:is_descendant_of(hero)))
print("  BruceWillis:is_descendant_of(BruceWillis)    => " .. tostring(BruceWillis:is_descendant_of(BruceWillis)))
print("  BruceWillis:is_descendant_of(john_mcclane)   => " .. tostring(BruceWillis:is_descendant_of(john_mcclane)))
print("  john_mcclane:is_descendant_of(Hero)          => " .. tostring(john_mcclane:is_descendant_of(Hero)))
print("  john_mcclane:is_descendant_of(hero)          => " .. tostring(john_mcclane:is_descendant_of(hero)))
print("  john_mcclane:is_descendant_of(BruceWillis)   => " .. tostring(john_mcclane:is_descendant_of(BruceWillis)))
print("  john_mcclane:is_descendant_of(john_mcclane)  => " .. tostring(john_mcclane:is_descendant_of(john_mcclane)))
print("  Hero:is_kind_of(Hero)                        => " .. tostring(Hero:is_kind_of(Hero)))
print("  Hero:is_kind_of(hero)                        => " .. tostring(Hero:is_kind_of(hero)))
print("  Hero:is_kind_of(BruceWillis)                 => " .. tostring(Hero:is_kind_of(BruceWillis)))
print("  Hero:is_kind_of(john_mcclane)                => " .. tostring(Hero:is_kind_of(john_mcclane)))
print("  hero:is_kind_of(Hero)                        => " .. tostring(hero:is_kind_of(Hero)))
print("  hero:is_kind_of(hero)                        => " .. tostring(hero:is_kind_of(hero)))
print("  hero:is_kind_of(BruceWillis)                 => " .. tostring(hero:is_kind_of(BruceWillis)))
print("  hero:is_kind_of(john_mcclane)                => " .. tostring(hero:is_kind_of(john_mcclane)))
print("  BruceWillis:is_kind_of(Hero)                 => " .. tostring(BruceWillis:is_kind_of(Hero)))
print("  BruceWillis:is_kind_of(hero)                 => " .. tostring(BruceWillis:is_kind_of(hero)))
print("  BruceWillis:is_kind_of(BruceWillis)          => " .. tostring(BruceWillis:is_kind_of(BruceWillis)))
print("  BruceWillis:is_kind_of(john_mcclane)         => " .. tostring(BruceWillis:is_kind_of(john_mcclane)))
print("  john_mcclane:is_kind_of(Hero)                => " .. tostring(john_mcclane:is_kind_of(Hero)))
print("  john_mcclane:is_kind_of(hero)                => " .. tostring(john_mcclane:is_kind_of(hero)))
print("  john_mcclane:is_kind_of(BruceWillis)         => " .. tostring(john_mcclane:is_kind_of(BruceWillis)))
print("  john_mcclane:is_kind_of(john_mcclane)        => " .. tostring(john_mcclane:is_kind_of(john_mcclane)))
